services:
  - type: web
    name: nyc-taxi-explorer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
